In [3]:
import numpy as np
np.full(4,3)
np.ones(3)

array([1., 1., 1.])

In [4]:
np.arange(3)

array([0, 1, 2])

In [6]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [7]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
import pandas as pd

In [12]:
df = [['jennifer', 34, 'seoul'], ['susan', 22, 'new york']]

In [13]:
df

[['jennifer', 34, 'seoul'], ['susan', 22, 'new york']]

In [15]:
new_df = np.array(df)

In [17]:
new_df

array([['jennifer', '34', 'seoul'],
       ['susan', '22', 'new york']], dtype='<U8')

In [18]:
series = [
    pd.Series(['june', 34, 'seoul']),
    pd.Series(['jane', 43, 'london']),
    pd.Series(['annaka', 42, 'saltlakecity'])
]

In [19]:
series

[0     june
 1       34
 2    seoul
 dtype: object,
 0      jane
 1        43
 2    london
 dtype: object,
 0          annaka
 1              42
 2    saltlakecity
 dtype: object]

In [21]:
df_series = pd.DataFrame(series)

In [22]:
df_series

0   1             2
0    june  34         seoul
1    jane  43        london
2  annaka  42  saltlakecity

In [25]:
df_new_df = pd.DataFrame(new_df)

In [26]:
df_new_df

0   1         2
0  jennifer  34     seoul
1     susan  22  new york

In [27]:
names = ['dongwook', 'sineui', 'ikjoong', 'yoonsoo']
english_scores = [50, 89, 68, 88]
math_scores = [86, 31, 91, 75]

dict1 = {
    'name': names, 
    'english_score': english_scores, 
    'math_score': math_scores
}

dict2 = {
    'name': np.array(names), 
    'english_score': np.array(english_scores), 
    'math_score': np.array(math_scores)
}

dict3 = {
    'name': pd.Series(names), 
    'english_score': pd.Series(english_scores), 
    'math_score': pd.Series(math_scores)
}

#all results same
df1 = pd.DataFrame(dict1)
df2 = pd.DataFrame(dict2)
df3 = pd.DataFrame(dict3)

print(df1)


       name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75


In [28]:
my_list = [
    {'name': 'dongwook', 'english_score': 50, 'math_score': 86},
    {'name': 'sineui', 'english_score': 89, 'math_score': 31},
    {'name': 'ikjoong', 'english_score': 68, 'math_score': 91},
    {'name': 'yoonsoo', 'english_score': 88, 'math_score': 75}
]

df = pd.DataFrame(my_list)
print(df)

       name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75


In [34]:
#pandas datatype-example
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]
my_df = pd.DataFrame(two_dimensional_list, columns=['name', 'english_score', 'math_score'], index=['a', 'b', 'c', 'd'])
print(my_df.dtypes)

#int64 = integer
#float64 = float
#object = text
#bool = boolean(true or false)
#datetime64 = date and time
#category = category 

name             object
english_score     int64
math_score        int64
dtype: object
